# Generated by Django 5.0 on 2024-03-01 15:40

import django.db.models.deletion
import markupfield.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0002_alter_matrizriesgo_gravedad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Columna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Postit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('columna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='gestor.columna')),
            ],
        ),
        migrations.AddField(
            model_name='proyecto',
            name='columna',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='matrizriesgo',
            name='gravedad',
            field=models.CharField(choices=[('bajo1', 'Bajo'), ('medio', 'Medio'), ('alto1', 'Alto'), ('Bajo2', 'Muy Bajo'), ('alto2', 'Muy Alto')], max_length=20),
        ),
        migrations.AlterField(
            model_name='matrizriesgo',
            name='probavilidad',
            field=models.CharField(choices=[('bajo1', 'Bajo'), ('medio', 'Medio'), ('alto1', 'Alto'), ('Bajo2', 'Muy Bajo'), ('alto2', 'Muy Alto')], max_length=20),
        ),
        migrations.CreateModel(
            name='Tablero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('proyect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.proyecto')),
            ],
        ),
        migrations.AddField(
            model_name='columna',
            name='tablero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columnas', to='gestor.tablero'),
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('postit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor.postit')),
                ('descripcion', markupfield.fields.MarkupField(rendered_field=True)),
                ('descripcion_markup_type', models.CharField(blank=True, choices=[('', '--'), ('html', 'HTML'), ('plain', 'Plain'), ('markdown', 'Markdown')], default=None, max_length=30, null=True)),
                ('_descripcion_rendered', models.TextField(editable=False)),
                ('participantes', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            bases=('gestor.postit',),
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to='recursos')),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.tarjeta')),
            ],
        ),
    ]
